version: "3.8"

services:
  # --- Serviço 1: Nossa API (Producer/Consumer HTTP) ---
  api:
    build: .
    container_name: churn_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/churn_db
    depends_on:
      - db
    volumes:
      - .:/app

  # --- Serviço 2: Frontend (React/Vite) ---
  frontend:
    build: ./frontend
    container_name: churn_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      # Aponta para o serviço 'api' dentro da rede do Docker
      - API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      # Monta o código local para permitir hot-reload
      - ./frontend:/app
      # Evita que o node_modules local (Windows) sobrescreva o do container (Linux)
      - /app/node_modules

  # --- Serviço 3: Banco de Dados (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: churn_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=churn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- Serviço 4: Analytics (Grafana) ---
  grafana:
    image: grafana/grafana-oss:latest
    container_name: churn_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./analytics/provisioning:/etc/grafana/provisioning
      - ./analytics/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - db

volumes:
  postgres_data:
